/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : ADC_ANALOG.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08QE128CLK
**     Component   : ADC
**     Version     : Component 01.667, Driver 01.30, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2014-05-12, 14:12, # CodeGen: 51
**     Abstract    :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings    :
**          Component name                                 : ADC_ANALOG
**          A/D converter                                  : ADC
**          Sharing                                        : Disabled
**          Interrupt service/event                        : Enabled
**            A/D interrupt                                : Vadc
**            A/D interrupt priority                       : medium priority
**          A/D channels                                   : 6
**            Channel0                                     : 
**              A/D channel (pin)                          : PTA0_KBI1P0_TPM1CH0_ADP0_ACMP1PLUS
**              A/D channel (pin) signal                   : POT
**            Channel1                                     : 
**              A/D channel (pin)                          : PTA2_KBI1P2_SDA1_ADP2
**              A/D channel (pin) signal                   : ACCELX
**            Channel2                                     : 
**              A/D channel (pin)                          : PTA3_KBI1P3_SCL1_ADP3
**              A/D channel (pin) signal                   : ACCELY
**            Channel3                                     : 
**              A/D channel (pin)                          : PTB3_KBI1P7_MOSI1_ADP7
**              A/D channel (pin) signal                   : ACCELZ
**            Channel4                                     : 
**              A/D channel (pin)                          : PTF0_ADP10
**              A/D channel (pin) signal                   : PIEZO
**            Channel5                                     : 
**              A/D channel (pin)                          : PTF1_ADP11
**              A/D channel (pin) signal                   : 
**          A/D resolution                                 : 8 bits
**          Conversion time                                : 3.178914 µs
**          Low-power mode                                 : Disabled
**          Sample time                                    : short
**          Internal trigger                               : Disabled
**          Number of conversions                          : 1
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**          High input limit                               : 1
**          Low input limit                                : 0
**          Get value directly                             : yes
**          Wait for result                                : yes
**     Contents    :
**         Measure      - byte ADC_ANALOG_Measure(bool WaitForResult);
**         MeasureChan  - byte ADC_ANALOG_MeasureChan(bool WaitForResult, byte Channel);
**         GetValue     - byte ADC_ANALOG_GetValue(void* Values);
**         GetChanValue - byte ADC_ANALOG_GetChanValue(byte Channel, void* Value);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE ADC_ANALOG. */

#include "Events.h"
#include "ADC_ANALOG.h"



static void ClrSumV(void);
/*
** ===================================================================
**     Method      :  ClrSumV (component ADC)
**
**     Description :
**         The method clears the internal buffers used to store sum of a 
**         number of last conversions.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define STOP            0x00U          /* STOP state           */
#define MEASURE         0x01U          /* MESURE state         */
#define CONTINUOUS      0x02U          /* CONTINUOS state      */
#define SINGLE          0x03U          /* SINGLE state         */

static const  byte Table[6] = {0x01U,0x02U,0x04U,0x08U,0x10U,0x20U};  /* Table of mask constants */

static const  byte Channels[6] = {0x40U,0x42U,0x43U,0x47U,0x4AU,0x4BU};  /* Contents for the device control register */

static volatile byte OutFlg;           /* Measurement finish flag */
static volatile byte SumChan;          /* Number of measured channels */
static volatile byte ModeFlg;          /* Current state of device */

volatile byte ADC_ANALOG_OutV[6];      /* Sum of measured values */





/*
** ===================================================================
**     Method      :  ADC_ANALOG_Interrupt (component ADC)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(ADC_ANALOG_Interrupt)
{
  if (ModeFlg != SINGLE) {
    ADC_ANALOG_OutV[SumChan] = ADCRL;  /* Save measured value */
    SumChan++;                         /* Number of measurement */
    if (SumChan == 6U) {               /* Is number of measurement equal to the number of conversions? */
      SumChan = 0U;                    /* If yes then set the number of measurement to 0 */
      OutFlg = 0x3FU;                  /* Measured values are available */
      ADC_ANALOG_OnEnd();              /* Invoke user event */
      ModeFlg = STOP;                  /* Set the device to the stop mode */
      return;                          /* Return from interrupt */
    }
    ADCSC1 = Channels[SumChan];        /* Start measurement of next channel */
  }
  else {
    ADC_ANALOG_OutV[SumChan] = ADCRL;  /* Save measured value */
    /*lint -save  -e740 -e931 Disable MISRA rule (1.2) checking. */
    OutFlg |= Table[SumChan];          /* Value of measured channel is available */
    /*lint -restore Enable MISRA rule (1.2) checking. */
    ADC_ANALOG_OnEnd();                /* Invoke user event */
    ModeFlg = STOP;                    /* Set the device to the stop mode */
  }
}

/*
** ===================================================================
**     Method      :  ClrSumV (component ADC)
**
**     Description :
**         The method clears the internal buffers used to store sum of a 
**         number of last conversions.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void ClrSumV(void)
{
  ADC_ANALOG_OutV[0] = 0U;             /* Set variable for storing measured values to 0 */
  ADC_ANALOG_OutV[1] = 0U;             /* Set variable for storing measured values to 0 */
  ADC_ANALOG_OutV[2] = 0U;             /* Set variable for storing measured values to 0 */
  ADC_ANALOG_OutV[3] = 0U;             /* Set variable for storing measured values to 0 */
  ADC_ANALOG_OutV[4] = 0U;             /* Set variable for storing measured values to 0 */
  ADC_ANALOG_OutV[5] = 0U;             /* Set variable for storing measured values to 0 */
}

/*
** ===================================================================
**     Method      :  ADC_ANALOG_HWEnDi (component ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void ADC_ANALOG_HWEnDi(void)
{
  if (ModeFlg) {                       /* Start or stop measurement? */
    if (ModeFlg != SINGLE) {
      OutFlg = 0U;                     /* Output values aren't available */
      SumChan = 0U;                    /* Set the number of measured channels to 0 */
      ClrSumV();                       /* Clear measured values */
    }
    else {
      /*lint -save  -e740 -e931 Disable MISRA rule (1.2) checking. */
      OutFlg &= (byte)(~(byte)Table[SumChan]); /* Output value isn't available */
      /*lint -restore Enable MISRA rule (1.2) checking. */
      ADC_ANALOG_OutV[SumChan] = 0U;   /* Set variable for storing measured values to 0 */
    }
    ADCSC1 = Channels[SumChan];        /* If yes then start the conversion */
  }
}

/*
** ===================================================================
**     Method      :  ADC_ANALOG_Measure (component ADC)
**
**     Description :
**         This method performs one measurement on all channels that
**         are set in the component inspector. (Note: If the <number of
**         conversions> is more than one the conversion of A/D channels
**         is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of a
**                           conversion. If <interrupt service> is
**                           disabled, A/D peripheral doesn't support
**                           measuring all channels at once or Autoscan
**                           mode property isn't enabled and at the same
**                           time the <number of channels> is greater
**                           than 1, then the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time. If the <interrupt
**                           service> is disabled and a <number of
**                           conversions> is greater than 1, the
**                           parameter is ignored and the method also
**                           waits for each result every time.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
** ===================================================================
*/
#pragma MESSAGE DISABLE C5703 /* WARNING C5703: Parameter declared but not referenced */
byte ADC_ANALOG_Measure(bool WaitForResult)
{
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = MEASURE;                   /* Set state of device to the measure mode */
  ADC_ANALOG_HWEnDi();                 /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg == MEASURE) {}      /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_ANALOG_MeasureChan (component ADC)
**
**     Description :
**         This method performs measurement on one channel. (Note: If
**         the <number of conversions> is more than one the conversion
**         of the A/D channel is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result of
**                           conversion. If the <interrupt service> is
**                           disabled and at the same time a <number of
**                           conversions> is greater than 1, the
**                           WaitForResult parameter is ignored and the
**                           method waits for each result every time.
**         Channel         - Channel number. If only one
**                           channel in the component is set this
**                           parameter is ignored, because the parameter
**                           is set inside this method.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
**                           ERR_RANGE - Parameter "Channel" out of range
** ===================================================================
*/
byte ADC_ANALOG_MeasureChan(bool WaitForResult,byte Channel)
{
  if (Channel >= 6U) {                 /* Is channel number greater than or equal to 6 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = SINGLE;                    /* Set state of device to the measure mode */
  SumChan = Channel;                   /* Set required channel */
  ADC_ANALOG_HWEnDi();                 /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg == SINGLE) {}       /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_ANALOG_GetValue (component ADC)
**
**     Description :
**         Returns the last measured values for all channels. Format
**         and width of the value is a native format of the A/D
**         converter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that contains
**                           the measured data. Data type is a byte, a
**                           word or an int. It depends on the supported
**                           modes, resolution, etc. of the AD converter.
**                           See the Version specific information for
**                           the current CPU in <General Info>.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
byte ADC_ANALOG_GetValue(void *Values)
{
  if (OutFlg != 0x3FU) {               /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  ((byte*)Values)[0] = ADC_ANALOG_OutV[0]; /* Save measured values to the output buffer */
  ((byte*)Values)[1] = ADC_ANALOG_OutV[1]; /* Save measured values to the output buffer */
  ((byte*)Values)[2] = ADC_ANALOG_OutV[2]; /* Save measured values to the output buffer */
  ((byte*)Values)[3] = ADC_ANALOG_OutV[3]; /* Save measured values to the output buffer */
  ((byte*)Values)[4] = ADC_ANALOG_OutV[4]; /* Save measured values to the output buffer */
  ((byte*)Values)[5] = ADC_ANALOG_OutV[5]; /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_ANALOG_GetChanValue (component ADC)
**
**     Description :
**         Returns the last measured value of the required channel.
**         Format and width of the value is a native format of the A/D
**         converter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Channel         - Channel number. If only one
**                           channel in the component is set then this
**                           parameter is ignored.
**       * Value           - Pointer to the measured value. Data
**                           type is a byte, a word or an int. It
**                           depends on the supported modes, resolution,
**                           etc. of the AD converter. See the Version
**                           specific information for the current CPU in
**                           <General Info>.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_RANGE - Parameter "Channel" out of
**                           range
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
** ===================================================================
*/
byte ADC_ANALOG_GetChanValue(byte Channel,void* Value)
{
  if (Channel >= 6U) {                 /* Is channel number greater than or equal to 6 */
    return ERR_RANGE;                  /* If yes then error */
  }
  if ((OutFlg & Table[Channel]) == 0U) { /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *(byte*)Value = ADC_ANALOG_OutV[Channel]; /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_ANALOG_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void ADC_ANALOG_Init(void)
{
  /* ADCSC1: COCO=0,AIEN=0,ADCO=0,ADCH4=1,ADCH3=1,ADCH2=1,ADCH1=1,ADCH0=1 */
  setReg8(ADCSC1, 0x1FU);              /* Disable the module */ 
  /* ADCSC2: ADACT=0,ADTRG=0,ACFE=0,ACFGT=0,??=0,??=0,??=0,??=0 */
  setReg8(ADCSC2, 0x00U);              /* Disable HW trigger and autocompare */ 
  OutFlg = 0U;                         /* No measured value */
  ModeFlg = STOP;                      /* Device isn't running */
  /* ADCCFG: ADLPC=0,ADIV1=1,ADIV0=0,ADLSMP=0,MODE1=0,MODE0=0,ADICLK1=0,ADICLK0=0 */
  setReg8(ADCCFG, 0x40U);              /* Set prescaler bits */ 
}


/* END ADC_ANALOG. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
