/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : CMP1.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08QE128CLK
**     Component   : ExtInt
**     Version     : Component 02.104, Driver 01.24, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2014-05-18, 18:01, # CodeGen: 55
**     Abstract    :
**         This component "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The component uses one pin which generates interrupt on 
**         selected edge.
**     Settings    :
**         Interrupt name              : Vkeyboard
**         User handling procedure     : CMP1_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       1             |  PTD1_KBI2P1_MOSI2
**             ----------------------------------------------------
**
**         Port name                   : PTD
**
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Signal edge/level           : falling
**         Priority                    : 
**         Pull option                 : off
**         Initial state               : Enabled
**
**
**         Port data register          : PTDD      [$0006]
**         Port control register       : PTDDD     [$0007]
**     Contents    :
**         GetVal - bool CMP1_GetVal(void);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#include "CMP1.h"

/*Including shared modules, which are used for all project*/

#include "Events.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  CMP1_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the components event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CMP1_Interrupt)
{
  KBI2SC_KBACK = 1U;                   /* Clear the interrupt flag */
  CMP1_OnInterrupt();                  /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  CMP1_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the component.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           <false> - logical "0" (Low level) <true> -
**                           logical "1" (High level)
** ===================================================================
*/
/*
bool CMP1_GetVal(void)

**      This method is implemented as macro. See CMP1.h file.      **
*/

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
