/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : ControlZ.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08QE128CLK
**     Component   : BitIO
**     Version     : Component 02.086, Driver 03.27, CPU db: 3.00.067
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2014-05-24, 19:50, # CodeGen: 59
**     Abstract    :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings    :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       52            |  PTF1_ADP11
**             ----------------------------------------------------
**
**         Port name                   : PTF
**
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTFD      [$000A]
**         Port control register       : PTFDD     [$000B]
**
**         Optimization for            : speed
**     Contents    :
**         SetDir - void ControlZ_SetDir(bool Dir);
**         GetVal - bool ControlZ_GetVal(void);
**         PutVal - void ControlZ_PutVal(bool Val);
**         ClrVal - void ControlZ_ClrVal(void);
**         SetVal - void ControlZ_SetVal(void);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE ControlZ. */

#include "ControlZ.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  ControlZ_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool ControlZ_GetVal(void)

**  This method is implemented as a macro. See ControlZ.h file.  **
*/

/*
** ===================================================================
**     Method      :  ControlZ_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void ControlZ_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PTFD, 0x02U);          /* PTFD1=0x01U */
    Shadow_PTF |= 0x02U;               /* Set-up shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTFD, 0x02U);          /* PTFD1=0x00U */
    Shadow_PTF &= 0xFDU;               /* Set-up shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  ControlZ_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ControlZ_ClrVal(void)

**  This method is implemented as a macro. See ControlZ.h file.  **
*/

/*
** ===================================================================
**     Method      :  ControlZ_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void ControlZ_SetVal(void)

**  This method is implemented as a macro. See ControlZ.h file.  **
*/

/*
** ===================================================================
**     Method      :  ControlZ_SetDir (component BitIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void ControlZ_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTFD, (getReg8(PTFD) & (byte)(~(byte)0x02U)) | (Shadow_PTF & 0x02U)); /* PTFD1=Shadow_PTF[bit 1] */
    setReg8Bits(PTFDD, 0x02U);         /* PTFDD1=0x01U */
  } else { /* !Dir */
    clrReg8Bits(PTFDD, 0x02U);         /* PTFDD1=0x00U */
  } /* !Dir */
}


/* END ControlZ. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
